FROM python:3.11-slim
WORKDIR /app
COPY ./todo_backend /app
RUN pip install --upgrade pip && pip install -r requirements.txt && pip install django-filter
EXPOSE 8000
CMD ["sh", "-c", "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]
